//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeService.DataAccess {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeService.DataAccess.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO Companies (&quot;Name&quot;, &quot;Inn&quot;)
        ///VALUES (@Name, @Inn)
        ///RETURNING &quot;Id&quot;.
        /// </summary>
        internal static string AddCompany {
            get {
                return ResourceManager.GetString("AddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO &quot;Departments&quot; (&quot;Name&quot;, &quot;Phone&quot;)
        ///VALUES (@Name, @Phone)
        ///RETURNING &quot;Id&quot;.
        /// </summary>
        internal static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO &quot;Employees&quot; (&quot;Name&quot;, &quot;Surname&quot;, &quot;Phone&quot;, &quot;CompanyId&quot;, &quot;PassportId&quot;, &quot;DepartmentId&quot;)
        ///VALUES (@Name, @Surname, @Phone, @CompanyId, @PassportId, @DepartmentId)
        ///RETURNING &quot;Id&quot;.
        /// </summary>
        internal static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO &quot;Passports&quot; (&quot;Type&quot;, &quot;Number&quot;)
        ///VALUES (@Type, @Number)
        ///RETURNING &quot;Id&quot;.
        /// </summary>
        internal static string AddPassport {
            get {
                return ResourceManager.GetString("AddPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM &quot;Companies&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string DeleteCompany {
            get {
                return ResourceManager.GetString("DeleteCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM &quot;Departments&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string DeleteDepartment {
            get {
                return ResourceManager.GetString("DeleteDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM &quot;Employees&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM &quot;Passports&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string DeletePassport {
            get {
                return ResourceManager.GetString("DeletePassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,
        ///	   &quot;Name&quot;,
        ///	   &quot;Inn&quot;
        ///FROM &quot;Companies&quot;.
        /// </summary>
        internal static string GetAllCompanies {
            get {
                return ResourceManager.GetString("GetAllCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,
        ///	   &quot;Name&quot;,
        ///	   &quot;Phone&quot;
        ///FROM &quot;Departments&quot;.
        /// </summary>
        internal static string GetAllDepartments {
            get {
                return ResourceManager.GetString("GetAllDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,
        ///	   &quot;Name&quot;,
        ///	   &quot;Surname&quot;,
        ///	   &quot;Phone&quot;,
        ///	   &quot;CompanyId&quot;,
        ///	   &quot;PassportId&quot;,
        ///	   &quot;DepartmentId&quot;
        ///FROM &quot;Employees&quot;.
        /// </summary>
        internal static string GetAllEmployees {
            get {
                return ResourceManager.GetString("GetAllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,
        ///	   &quot;Name&quot;,
        ///	   &quot;Inn&quot;
        ///FROM &quot;Companies&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string GetCompanyById {
            get {
                return ResourceManager.GetString("GetCompanyById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,
        ///	   &quot;Name&quot;,
        ///	   &quot;Phone&quot;
        ///FROM &quot;Departments&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string GetDepartmentById {
            get {
                return ResourceManager.GetString("GetDepartmentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,
        ///	   &quot;Name&quot;,
        ///	   &quot;Surname&quot;,
        ///	   &quot;Phone&quot;,
        ///	   &quot;CompanyId&quot;,
        ///	   &quot;PassportId&quot;,
        ///	   &quot;DepartmentId&quot;
        ///FROM &quot;Employees&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string GetEmployeeById {
            get {
                return ResourceManager.GetString("GetEmployeeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,
        ///	   &quot;Name&quot;,
        ///	   &quot;Surname&quot;,
        ///	   &quot;Phone&quot;,
        ///	   &quot;CompanyId&quot;,
        ///	   &quot;PassportId&quot;,
        ///	   &quot;DepartmentId&quot;
        ///FROM &quot;Employees&quot;
        ///WHERE &quot;CompanyId&quot; = @CompanyId.
        /// </summary>
        internal static string GetEmployeesByCompanyId {
            get {
                return ResourceManager.GetString("GetEmployeesByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,
        ///	   &quot;Name&quot;,
        ///	   &quot;Surname&quot;,
        ///	   &quot;Phone&quot;,
        ///	   &quot;CompanyId&quot;,
        ///	   &quot;PassportId&quot;,
        ///	   &quot;DepartmentId&quot;
        ///FROM &quot;Employees&quot;
        ///WHERE &quot;CompanyId&quot; = @CompanyId AND &quot;DepartmentId&quot; = @DepartmentId.
        /// </summary>
        internal static string GetEmployeesByCompanyIdAndDepartmentId {
            get {
                return ResourceManager.GetString("GetEmployeesByCompanyIdAndDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT &quot;Id&quot;,
        ///	   &quot;Type&quot;,
        ///	   &quot;Number&quot;
        ///FROM &quot;Passports&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string GetPassportById {
            get {
                return ResourceManager.GetString("GetPassportById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT EXISTS(
        ///	SELECT 1 FROM &quot;Companies&quot;
        ///	WHERE &quot;Id&quot; = 1
        ///).
        /// </summary>
        internal static string IsCompanyExists {
            get {
                return ResourceManager.GetString("IsCompanyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT EXISTS(
        ///	SELECT 1 FROM &quot;Departments&quot;
        ///	WHERE &quot;Id&quot; = 1
        ///).
        /// </summary>
        internal static string IsDepartmentExists {
            get {
                return ResourceManager.GetString("IsDepartmentExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT EXISTS(
        ///	SELECT 1 FROM &quot;Employees&quot;
        ///	WHERE &quot;Id&quot; = 1
        ///).
        /// </summary>
        internal static string IsEmployeeExists {
            get {
                return ResourceManager.GetString("IsEmployeeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE &quot;Companies&quot;
        ///SET 
        ///    &quot;Name&quot; = COALESCE(@Name, &quot;Name&quot;)
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string UpdateCompany {
            get {
                return ResourceManager.GetString("UpdateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE &quot;Departments&quot;
        ///SET 
        ///    &quot;Name&quot; = COALESCE(@Name, &quot;Name&quot;),
        ///    &quot;Phone&quot; = COALESCE(@Phone, &quot;Phone&quot;)
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string UpdateDepartment {
            get {
                return ResourceManager.GetString("UpdateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE &quot;Employees&quot;
        ///SET 
        ///	&quot;Name&quot; = COALESCE(@Name, &quot;Name&quot;),
        ///	&quot;Surname&quot; = COALESCE(@Surname, &quot;Surname&quot;),
        ///	&quot;Phone&quot; = COALESCE(@Phone, &quot;Phone&quot;),
        ///	&quot;CompanyId&quot; = CASE WHEN @CompanyId &gt; 0 THEN @CompanyId ELSE &quot;CompanyId&quot; END,
        ///	&quot;PassportId&quot; = CASE WHEN @PassportId &gt; 0 THEN @PassportId ELSE &quot;PassportId&quot; END,
        ///	&quot;DepartmentId&quot; = CASE WHEN @DepartmentId &gt; 0 THEN @DepartmentId ELSE &quot;DepartmentId&quot; END
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string UpdateEmployee {
            get {
                return ResourceManager.GetString("UpdateEmployee", resourceCulture);
            }
        }
    }
}
